spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/portfolio
    username: portfolio
    password: portfolio

server:
  address: 127.0.0.1
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      probes:
        enabled: true
